# Generated by Django 4.1.1 on 2023-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='cv_link',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='user_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
